# Generated by Django 4.2.6 on 2023-11-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rauser',
            name='ra_email',
            field=models.EmailField(default=None, max_length=254),
        ),
    ]
