# Generated by Django 4.2.6 on 2023-11-03 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='TaskId',
            new_name='id',
        ),
    ]
