# Generated by Django 4.2.6 on 2023-11-03 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rauser_email_rauser_first_name_rauser_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rauser',
            name='password',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
