# Generated by Django 4.2.7 on 2023-11-08 01:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_resident_creates_ticket_fk_resident_comment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotations',
            fields=[
                ('annotate_id', models.AutoField(primary_key=True, serialize=False)),
                ('annotations', models.TextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fk_task_annotations', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='accounts.task')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('date_posted', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fk_task_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='accounts.task')),
            ],
        ),
        migrations.RemoveField(
            model_name='comment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.DeleteModel(
            name='Annotation',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
