# Generated by Django 4.2.5 on 2023-10-18 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'To Do'), (2, 'In Progress'), (3, 'Done')]),
        ),
    ]
