# Generated by Django 4.2.5 on 2023-10-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_task_assingor_task_date_posted_task_floor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='is_manager',
        ),
        migrations.AddField(
            model_name='manageruser',
            name='is_admin',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='manageruser',
            name='is_r_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='manageruser',
            name='is_resident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rauser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rauser',
            name='is_r_a',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rauser',
            name='is_resident',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentuser',
            name='is_r_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='residentuser',
            name='is_resident',
            field=models.BooleanField(default=True),
        ),
    ]
