# Generated by Django 4.2.6 on 2023-10-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_customuser_is_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
