# Generated by Django 4.2.6 on 2023-10-31 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_task_is_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_open',
        ),
    ]
